{% set name = "mrjob" %}
{% set version = "0.7.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "27f88870d31b85c27017109fa8a190dd7661b976eaa3488608f8f491fcb64a91" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  entry_points:
    - mrjob = mrjob.cmd:main
    - mrjob-2 = mrjob.cmd:main  # [py2k]
    - mrjob-3 = mrjob.cmd:main  # [py3k]
    - mrjob-2.7 = mrjob.cmd:main  # [py27]
    - mrjob-3.6 = mrjob.cmd:main  # [py36]
    - mrjob-3.7 = mrjob.cmd:main  # [py37]   
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - ujson
    - boto3 >=1.4.6
    - botocore >=1.6.0
    - pyyaml >=3.08
    - google-api-python-client >=1.5.0
    - rapidjson  # [py3k]

test:
  imports:
    - mrjob
    - mrjob.examples
    - mrjob.examples.mr_postfix_bounce
    - mrjob.examples.mr_travelling_salesman
    - mrjob.fs
    - mrjob.logs
    - mrjob.tools
    - mrjob.tools.emr

  commands:
    - mrjob --help
    - mrjob-2 --help  # [py2k]
    - mrjob-3 --help  # [py3k]
    - mrjob-2.7 --help  # [py27]
    - mrjob-3.7 --help  # [py37]
    - mrjob-3.6 --help  # [py36]

about:
  home: https://github.com/Yelp/mrjob
  license_file: LICENSE.txt
  license: Apache 2.0
  license_family: Apache
  summary: 'Python MapReduce framework'
  dev_url: https://github.com/Yelp/mrjob
  doc_url: https://pythonhosted.org/mrjob/

extra:
  recipe-maintainers:
    - pmlandwehr
    - mariusvniekerk
